version: "3.1"

services:
  mysql:
    image: mysql:5.7.29
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --init-file /init.sql
    volumes:
      - ./sourcefiles/mysql:/var/lib/mysql
      - ./init.sql:/init.sql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: zlatkit-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    volumes:
      - ../:/application
      - ./sourcefiles/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  php-fpm:
    build: sourcefiles/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
      - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./sourcefiles/php-fpm/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/laravel-worker.conf" ]
  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    command: [ "redis-server", "--appendonly", "yes","--requirepass","redis" ]
    volumes:
      - ./sourcefiles/redis:/redis
    ports:
      - 6379:6379
